PROJECT := test
IARC    :=
DEFS    :=
INCS    := include
SRCS    := src/main.c
LIBS    :=
SCRIPT  :=
COMMON  := common

#----------------------------------------------------------#
include $(COMMON)/intros/make/stm8sdiscovery/makefile.iarc
#----------------------------------------------------------#

include $(COMMON)/startup/makefile
include $(COMMON)/api/makefile
include $(COMMON)/device/makefile
include $(COMMON)/intros/makefile

#----------------------------------------------------------#
include $(COMMON)/make/makefile
#----------------------------------------------------------#
